name: HREF Hodograph Grid Update

on:
  schedule:
    - cron: '30 4,16 * * *'
  workflow_dispatch:

jobs:
  build-hodographs:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial for pushing images
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libeccodes-dev

      - name: Install Python Libraries
        run: pip install numpy matplotlib cartopy pygrib metpy requests pytz

      - name: Run Hodograph Script
        run: python SPC_HODO_GRID.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Force create directory if script somehow failed to
          mkdir -p hodo_data
          
          # Add all files including new ones
          git add hodo_data/*.png
          
          if git diff --staged --quiet; then
            echo "No new images found to commit."
          else
            git commit -m "Update HREF SE Dynamics - $(date)"
            git push
          fi
